version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

  api:
    build: .
    command: npm run server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3000
